version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/**"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
